apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: SERVICE_NAME-secrets
  namespace: SERVICE_NAMESPACE
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-platform
    kind: ClusterSecretStore
  target:
    name: SERVICE_NAME-runtime
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: services/SERVICE_NAMESPACE/SERVICE_NAME

