---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-readonly-root-filesystem
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: require-readonly-rootfs
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: >-
          Containers must set securityContext.readOnlyRootFilesystem=true.
        foreach:
          - list: "request.object.spec.containers[]"
            pattern:
              securityContext:
                readOnlyRootFilesystem: true
