---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-platform-image-signatures
  annotations:
    policies.kyverno.io/title: Verify Platform Image Signatures
    policies.kyverno.io/category: Supply Chain Security
spec:
  validationFailureAction: Enforce
  background: false
  failurePolicy: Fail
  webhookTimeoutSeconds: 30
  rules:
    - name: verify-cosign-keyless-github-actions-signature
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
        - imageReferences:
            - "docker.io/ohanyere/*"
            - "ohanyere/*"
          mutateDigest: true
          verifyDigest: true
          required: true
          attestors:
            - count: 1
              entries:
                - keyless:
                    subjectRegExp: "^https://github\\.com/ohanyere/[^/]+/\\.github/workflows/[^@]+@refs/heads/main$"
                    issuer: https://token.actions.githubusercontent.com
                    rekor:
                      url: https://rekor.sigstore.dev
