apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-platform
spec:
  acme:
    email: platform-team@ohanyere.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-platform-account-key
    solvers:
      - http01:
          ingress:
            class: istio
