apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: idp-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: IDP-managed application repositories registered in the fleet registry.
  sourceRepos:
    - https://github.com/ohanyere/*.git
  destinations:
    - namespace: '*-dev'
      server: https://kubernetes.default.svc
    - namespace: '*-stage'
      server: https://kubernetes.default.svc
    - namespace: '*-prod'
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
