apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform-owned infrastructure and shared controls.
  sourceRepos:
    - https://github.com/ohanyere/platform-core.git
  destinations:
    - namespace: argocd
      server: https://kubernetes.default.svc
    - namespace: platform-*
      server: https://kubernetes.default.svc
    - namespace: istio-system
      server: https://kubernetes.default.svc
    - namespace: cert-manager
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
