apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-payments
  namespace: argocd
spec:
  description: Payments team applications.
  sourceRepos:
    - https://github.com/ohanyere/payments-*.git
  destinations:
    - namespace: payments-*
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  clusterResourceWhitelist: []
