apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: SERVICE_NAME
  namespace: SERVICE_NAMESPACE
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: SERVICE_NAME
  endpoints:
    - port: http-metrics
      path: /metrics
      interval: 30s

