apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xobjectbuckets.platform.ohanyere.com
spec:
  group: platform.ohanyere.com
  names:
    kind: XObjectBucket
    plural: xobjectbuckets
  claimNames:
    kind: ObjectBucket
    plural: objectbuckets
  versions:
    - name: v1alpha1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                parameters:
                  type: object
                  required:
                    - region
                  properties:
                    region:
                      type: string
                    versioning:
                      type: boolean
                      default: true
                    deletionPolicy:
                      type: string
                      enum: ["Delete", "Orphan"]
                      default: Orphan

